apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::136213906104:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-DPRGK9JZZKE5
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::136213906104:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-03T23:19:23Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "15620"
  uid: 09e0f49e-69e7-4e5e-b39b-76069d4616f2
